---
roles:

  puppet_master:
    provisioners:
      - type: pe_bootstrap
        role: :master
        answer_extras:
          - "q_puppetmaster_r10k_remote='ssh://git@bitbucket:7999/pup/control-repo.git'"
          - "q_puppetmaster_r10k_private_key=/etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa"
          - "q_puppetmaster_code_manager_auto_configure=y"
          - "q_puppetmaster_file_sync_service_enabled=y"

  get_modules:
    provisioners:
      - type: shell
        inline: "r10k puppetfile install --puppetfile /vagrant/Puppetfile --moduledir /etc/puppetlabs/code-staging/modules -v"
      - type: shell
        inline: "/bin/chown -R pe-puppet:pe-puppet /etc/puppetlabs/code-staging"

  setup_control_repo:
    provisioners:
      - type: shell
        inline: "mkdir -p /etc/puppetlabs/code-staging/environments/production"
      - type: shell
        inline: "yes | cp /vagrant/environment.conf /etc/puppetlabs/code-staging/environments/production/environment.conf"
      - type: shell
        inline: "yes | cp -r /vagrant/manifests /etc/puppetlabs/code-staging/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/site /etc/puppetlabs/code-staging/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/scripts /etc/puppetlabs/code-staging/environments/production/"
      - type: shell
        inline: "/bin/chown -R pe-puppet:pe-puppet /etc/puppetlabs/code-staging"

  puppet_agent:
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: pe_agent
        master_vm: 'puppet-master'
      - type: shell
        inline: 'puppet agent -t || echo "Waiting for the puppet run to finish, then restarting bitbucket to enable dev mode..."; while [[ -f /opt/puppetlabs/puppet/cache/state/agent_catalog_run.lock ]]; do sleep 5; echo -n "." ; done'
      - type: shell
        inline: 'service atlbitbucket restart'

  el-tools:
    provisioners:
      - type: shell
        inline: '/usr/bin/yum install telnet vim tree git -y'

  2_cpus:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--cpus', 2]

