---
roles:

  puppet_master:
    provisioners:
      - type: pe_bootstrap
        role: :master
        answer_extras:
          - "q_puppetmaster_r10k_remote='ssh://git@bitbucket:7999/pupp/control-repo.git'"
          - "q_puppetmaster_r10k_private_key=/etc/puppetlabs/puppetserver/ssh/id-control_repo.rsa"
          - "q_puppetmaster_code_manager_auto_configure=y"
          - "q_puppetmaster_file_sync_service_enabled=y"

  get_modules:
    provisioners:
      - type: shell
        inline: "r10k puppetfile install --puppetfile /vagrant/Puppetfile --moduledir /etc/puppetlabs/code-staging/modules -v"
      - type: shell
        inline: "/bin/chown -R pe-puppet:pe-puppet /etc/puppetlabs/code-staging"

  setup_control_repo:
    provisioners:
      - type: shell
        inline: "yes | cp /vagrant/environment.conf /etc/puppetlabs/code/environments/production/environment.conf"
      - type: shell
        inline: "yes | cp -r /vagrant/manifests /etc/puppetlabs/code/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/site /etc/puppetlabs/code/environments/production/"
      - type: shell
        inline: "yes | cp -r /vagrant/scripts /etc/puppetlabs/code/environments/production/"

  puppet_agent:
    provisioners:
      - type: pe_agent
        master_vm: 'puppet-master'

  el-tools:
    provisioners:
      - type: shell
        inline: '/usr/bin/yum install telnet vim tree git -y'

  2_cpus:
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--cpus', 2]

